### ISSUE TITLE
Add a Jupyter notebook example for Seshat API package

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat_api#1]
Notebook should:
- [x] Have associated setup instructions and venv 
- [x] Import the API package
- [x] Show retrieval of data into dataframes
- Could include using Cliopatria data via the API - new issue #3 
- Open a new issue to fix inconsistent pluralisation -  new issue #4

**Comment by kallewesterling** [comment]
Love this idea! thanks for this :)
