### ISSUE TITLE
🐛 [BUG] - Data missing from seshat-db api

### ISSUE THREAD

**Issue by matildaperuzzo** [Seshat-Global-History-Databank/seshat_api#30]
### Description

I found that some data points appear when I use the seshatdata api vs the seshat-db api. The seshatdata one seems to have data that seshat-db does not.

### Reproduction steps

`
from seshat_api import SeshatAPI
from seshat_api.sc import PolityTerritories, PopulationOfTheLargestSettlements
import pandas as pd

client = SeshatAPI(base_url="https://seshatdata.com/api") 

territories = PolityTerritories(client)
territories_df = pd.DataFrame(territories.get_all())
cond = territories_df.apply(lambda x: x.polity['new_name'] == 'kg_western_turk_khaganate', axis=1)
print(territories_df[cond])

client = SeshatAPI(base_url="https://seshat-db.com/api") 

territories = PolityTerritories(client)
territories_df = pd.DataFrame(territories.get_all())
cond = territories_df.apply(lambda x: x.polity['new_name'] == 'kg_western_turk_khaganate', axis=1)
print(territories_df[cond])

client = SeshatAPI(base_url="https://seshatdata.com/api") 

settlement = PopulationOfTheLargestSettlements(client)
settlement_df = pd.DataFrame(settlement.get_all())
cond = settlement_df.apply(lambda x: x.polity['new_name'] == 'ye_resulid_dyn', axis=1)
print(settlement_df[cond])

client = SeshatAPI(base_url="https://seshat-db.com/api") 

settlement = PopulationOfTheLargestSettlements(client)
settlement_df = pd.DataFrame(settlement.get_all())
cond = settlement_df.apply(lambda x: x.polity['new_name'] == 'ye_resulid_dyn', axis=1)
print(settlement_df[cond])
`

### Error message

```bash
NA
```

### Definition of Done

- [ ] A fix for the bug has been developed on a branch.
- [ ] A pull request has been created for the new branch to be merged into the main branch.

**Comment by matildaperuzzo** [comment]
Things being moved around and renamed by RAs in seshat-db

**Comment by kallewesterling** [comment]
So this is no longer an active issue @matildaperuzzo -- just wanted to check in about that!
