### ISSUE TITLE
Remove API endpoints for sensitive fields

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat_api#5]
API endpoints and functions should be removed from the both Seshat repo and from this API for the following which should not be accessed via the API:

- [x] ResearchAssistants
    - `Polity_research_assistant`
    - `PolityResearchAssistantFilter`
    - `PolityResearchAssistantViewSet`
    - `research-assistants`
    - `PolityResearchAssistants`
- [x] PolityExperts
- [x] PolityEditors
- [x] PrivateComments
- [x] PrivateCommentsParts
- [x] Comments
- [x] CommentParts
- [x] CommentPartThroughCitations
- [x] ScpThroughCtn
- [x] Ra
- accounts
    - [x] Profiles
    - [x] seshat-tasks

**Comment by edwardchalstrey1** [comment]
We have discussed and this may not be necessary as these views are limited to admins anyway

**Comment by kallewesterling** [comment]
I think we can close this issue now, no?
